FROM arm32v7/debian:bullseye
MAINTAINER Sergio Fernández "acsdesk@protonmail.com"
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y libgdal-dev r-base locales libudunits2-dev libgeos-dev libproj-dev && rm -rf /var/lib/apt/lists/* && localedef -i es_ES -c -f UTF-8 -A /usr/share/locale/locale.alias es_ES.UTF-8
ENV LANG es_ES.utf8

RUN R -e "install.packages('remotes', repos='https://cloud.r-project.org/')"  # Install remotes to install github s2 package, otherwise broken. Delete next time these two lines
RUN R -e "remotes::install_github("r-spatial/s2")"
RUN R -e "install.packages(c('shiny', 'shinydashboard', 'shinyjs', 'rgdal', 'raster', 'sp', 'pxR', 'leaflet', 'plotKML', 'highcharter'), repos='https://cloud.r-project.org/')"


COPY Rprofile.site /usr/lib/R/etc/
RUN mkdir -p /root/secciones_censales
COPY . /root/secciones_censales

EXPOSE 8080
CMD ["R", "-e", "shiny::runApp('/root/secciones_censales', port = 8080, host = '0.0.0.0')"]

